### ISSUE TITLE
Убрать зависимости для тестов в devDeps

### ISSUE THREAD

**Issue by alexbaumgertner** [ivanlemeshev/nd-1#2]
В https://github.com/ivanlemeshev/nd-1/blob/master/task-1-3/package.json#L16-L17 зависимости
- chai
- sinon

указаны как `dependencies`, но код приложения от них не зависит, только тесты. Такие зависимости можно убрать в `devDependencies` — они не будут скачиваться, если мы захотим приложение сделать npm-модулем и подключить в другом приложении.

**Comment by ivanlemeshev** [comment]
Спасибо, перенёс зависимости в `devDependencies`.
